---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: fedora-19
  - name: fedora-20
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  - name: debian-7.4
    run_list: apt::default

suites:
- name: package
  run_list: ['recipe[asterisk]']
  attributes: {
    asterisk: {
      install_method: 'package',
      package: {
        repo: {
          enable: true
        }
      }
    }
  }
- name: source
  run_list: ['recipe[asterisk]']
  attributes: {
    asterisk: {}
  }
- name: unimrcp-pkg
  run_list: ['recipe[asterisk]', 'recipe[asterisk::unimrcp]']
  attributes: {
    asterisk: {
      install_method: 'package'
    }
  }
- name: unimrcp-src
  run_list: ['recipe[asterisk]', 'recipe[asterisk::unimrcp]']
  attributes: {
    asterisk: {}
  }
